### ISSUE TITLE
100m/s hit hard and no recovery despite generous (cheaty) settings

### ISSUE THREAD

**Issue by kuzetsa** [andyleap/DebRefund#2]
1. [output_log.txt](https://gist.github.com/kuzetsa/c864b6d1394ac9caf846)
2. [screenshot](http://i.imgur.com/Q6Q9DXd.png)
### config.txt.default

```
MinimumSpeedGreen = 300
MinimumSpeedYellow = 8000
SafeRecoveryPercent = 100
YellowMaxPercent = 99
YellowMinPercent = 90
UpdateCheck = false
```

---

Wait, something just occured to me -- is that config file inert unless I rename it?

**Comment by andyleap** [comment]
Need to rename config file to config.txt
