### ISSUE TITLE
Launch debris

### ISSUE THREAD

**Issue by futchm** [andyleap/DebRefund#4]
After what feels like the thousandth time recovering the launch scaffolding, I thought "Wouldn't it be nice if there were a mod that did this button mashfest for me."
Then I thought that it might be a simple matter to add that feature into this mod.

**Comment by andyleap** [comment]
The Launch Clamps, and for that matter anything on the pad, is automatically recovered the next time you prep a rocket for launch.  That's a part of stock KSP
