### ISSUE TITLE
DebRefund catching falling stages twice (doubling their monetary value)

### ISSUE THREAD

**Issue by kalizec** [andyleap/DebRefund#5]
Not entirely sure whether I've found a bug in this mod or not.

But I'm getting two 'recovered' messages for each recovered part and I'm also getting twice the funds.

I've added up all the contracts, both archived and current, and I've got more funds than I could've possibly gained.

I'm using DebRefund-1.0.12.

Modlist
MechJeb2
MechJebAllPods
KerbalEngineerRedux
EngineerAllPods
RealChute
DeadlyReentry
EditorExtensions
FerramAerospaceResearch
Higher_Part_Cost
KerbalJointReinforcement
KerbalAlarmClock
SelectRoot
KW Rocketry
PreciseNode
NavBallDockingAlignmnet
RemoteTech2
RLA_Stockalike
TacLifeSupport
Toolbar

First thing I'll try is disabling some of them to see whether I can reproduce it with just DebRefund (or some other mod).

[edit]

Did a quick test by starting a new Campaign. First launch with multiple stages == immediate doubling of recovered parts.

![2014-07-28_00001](https://cloud.githubusercontent.com/assets/6470421/3723941/4eaaddd6-1679-11e4-8004-04f0d80d1185.jpg)
![2014-07-28_00002](https://cloud.githubusercontent.com/assets/6470421/3723942/4eab7f84-1679-11e4-8072-a62b456ce4d0.jpg)

**Comment by kalizec** [comment]
Checked the output-log. DebRefund is throwing some NullReferenceExceptions.

Hosting the output.log at http://qequoia.nl/ksp/debrefund/output_log.txt

**Comment by andyleap** [comment]
This is a problem I need to work out, but the first easy solution is to delete the DebRefund.dll in the root of your GameData folder.  Considering the last version to not have a folder in the zip was 1.0.5, some of those null references(most?) may be coming from the old version

**Comment by kalizec** [comment]
Ah, just found out I had both 1.0.12 and an earlier version installed.
Hadn't noticed the earlier versions didn't have a folder in which they came.

Will check if the problem persists.

**Comment by kalizec** [comment]
And that fixed it.

Feeling a bit stupid now.
But now we know why each mod should have it's own folder.
