### ISSUE TITLE
Negative returns for KSO LFBs

### ISSUE THREAD

**Issue by Nerezza** [andyleap/DebRefund#6]
So, wanting to mimic the Nasa way, I strapped parachutes on the Liquid Fueled Boosters for the KSO. When they returned, however, I was surprised to see negative values on a green report (4m/s landingish) and I was confused on how recovering rocket parts could be costing me instead of saving me.

Here's a bunch of the lines from the part.cfg. I left out things like descriptions and effects, and hope I've left relevant information in. I'll have to wait until later today to fly my next STS, so it'll be awhile before I can get more information.

TechRequired = veryHeavyRocketry
entryCost = 24000
cost = 2850
category = Propulsion
subcategory = 0

attachRules = 0,1,1,1,0

mass = 3.75
dragModelType = default
maximum_drag = 0.2
minimum_drag = 0.2
angularDrag = 2
crashTolerance = 20
breakingForce = 200
breakingTorque = 200
maxTemp = 2900

stagingIcon = SOLID_BOOSTER

RESOURCE
{
 name = LiquidFuel
 amount = 2454.5454
 maxAmount = 2454.5454
}

RESOURCE
{
 name = Oxidizer
 amount = 3000
 maxAmount = 3000
}

**Comment by andyleap** [comment]
Assuming you have TweakScale, this is entirely a TweakScale issue, as I can duplicate it in stock landed vessel refunding without DebRefund installed
