### ISSUE TITLE
Launch clamps hitting hard

### ISSUE THREAD

**Issue by Dasvaldez** [andyleap/DebRefund#7]
After launching, I receive a message stating that the launch clamps (Launch stability enhancers) hit the ground hard and could not be recovered. Since they are bolted to the launch pad, this makes little sense. ;)

I am not able to replicate the issue consistently, and I have only seen it occur on a massive ship experiencing physics lag. The messages pop when the launchpad leaves physics range, at Altitude 2.5km. 

Output.log is here: https://www.dropbox.com/s/7khxyhs9rb5tk4m/LaunchClampDebris_KSP.log

The issue was also captured in a twitch stream, complete with a shoutout to Vendan heh, available here:
http://www.twitch.tv/dasvaldez/c/4864053

You can see the messages start to pop @ 3:20, and the actual messages are shown ~3:50.

**Comment by somnambulistic** [comment]
To resolve this issue it might be helpful to exclude certain part classes or part names from DebRefund tracking. I'd like to exclude all launch clamps but also other recognized disposable parts like fairings.

**Comment by andyleap** [comment]
Added customizable list, default is launch clamps
